### ISSUE TITLE
Working through the lesson - corrections

### ISSUE THREAD

**Issue by katilp** [cms-opendata-workshop/workshop2022-lesson-cpp-root-python#12]
Work in progress

## Setup

- [x] Remove VM and CMSSW area
- [x] Update copy-paste warning, text dump does not exist
- [x] update submission link

## 02

Setting up
- [x] fix link docker exercises (2021 -> 2022)
- [x] docker run command would give an error as the container with that name already exists, replace with `docker start -i my_root`
- [x] remove comment on linux, it's the same for all
- [x] cd not needed /code is the shared area

You first...
- [x] vi and nano are not particularly popular, and as the editing is on the local computer, we should tell them to use their normal editor
- [x] for compilation, remind to go to the container

## 03

ROOT terminology, in getting the code
- [x] Linux or Mac -> in your local bash terminal 
- [x] tell to go in the shared directory
- [x] give full path with wget command `wget https://raw.githubusercontent.com/cms-opendata-workshop/workshop2022-lesson-cpp-root-python/gh-pages/data/root_and_cpp_tutorial_source_code.tgz`

Write to a file

- [x] replace vi with the normal editor
- [x] the write_ROOT_file.cc in the tar file has double headers, remove line 1-8
- [x] Makefile does not work in the container, fix as in #11 
- [x] Fix Makefile in the tarball as well

Read from a file

- [x] Makefile does not work in the container, fix as in #11 

## 04

Filling a histogram
- [x] instruct editing on the local computer
- [x] Makefile does not work in the container, fix as in #11 
- [x] remind to go to the container for compile and run
- [x] for the graphics, remind VNC users to `start_vnc`
- [x] screenshots show environment with CMSSW_5_3_32 area, could use these instead (updated, but they are not of great quality)
  ![image](https://user-images.githubusercontent.com/5859918/179155813-97af8417-fdb6-42d6-af3d-39260de08f88.png)
  ![image](https://user-images.githubusercontent.com/5859918/179156021-b6e5ccb4-bae7-4221-94ce-26ac1475db4a.png)
- [x] before work assignment, tell to quit ROOT (or instruct to open the tree.root file in the TBrowser window)
- [x] after assignment, quit ROOT
- [x] stop_vnc and exit container

## 06

- [x] Mac and Linux -> on the bash terminal (valid also for WSL2)
- [x] Under making use of docker, change as in 02 for the python container
- [x] analsis -> analysis

## 07

- [x] add command `jupyter-lab --ip=0.0.0.0 --no-browser` for opening jupyter-lab in the container
- [x] change Mac and Linux -> on the bash terminal

## 08

- [x] `import time` needed for the code
- [x] plot.show() needed in (both script and notebook)

**Comment by katilp** [comment]
Thanks @mattbellis, this is a very nice lesson! I made the fixes as listed above after having run and checked all steps on the containers
